name: Continuous Integration

on:
    pull_request:
    push:
        branches: ['develop', 'main']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}

            - name: Prettier
              uses: creyD/prettier_action@v4.3
              with:
                  dry: True
                  prettier_options: --check .
